### ISSUE TITLE
geometries are not correclty casted

### ISSUE THREAD

**Issue by 3nids** [strk/fineltra#9]
### You cannot use ST_Srid on the output of ST_Fineltra:

```
select st_srid(ST_Fineltra(geometry_21781, 'chenyx06.chenyx06_triangles', 'the_geom_lv03', 'the_geom_lv95')) from mytable
``` 
> function st_srid(bytea) is not unique

### Trying to cast leads to error

```
select st_srid(ST_Fineltra(geometry_21781, 'chenyx06.chenyx06_triangles', 'the_geom_lv03', 'the_geom_lv95')::Geometry(LINESTRING,2056)) from mytable
``` 
> ERROR:  Geometry SRID (21781) does not match column SRID (2056)

### Even with this dummy try:

```
select st_srid(ST_Fineltra(geometry_21781, 'chenyx06.chenyx06_triangles', 'the_geom_lv03', 'the_geom_lv95')::Geometry(LINESTRING,21781)) from mytable
```
> Geometry SRID (2056) does not match column SRID (21781)

Any idea?

**Comment by strk** [comment]
Looks like you're getting geometries with mixed SRID in output.
How about just casting to ::geometry and analyze what's going on
separately ?

**Comment by 3nids** [comment]
Thanks for the hint.
Apparently, I have some 'LINESTRING EMPTY' and these are not converted to 2056 by ST_Finletra.
To me this still sounds like an issue, but at least I know how to deal with it.
Thanks again!

**Comment by strk** [comment]
I agree it's an issue, but is different from
"geometries are not correclty casted" so please
close this one and file a new one :)

**Comment by 3nids** [comment]
on the way!
